confs = {
    # Local lineitem
    "local_lineitem" : {
        'JAR' : '/Users/anil/Dev/repos/mdindex/build/libs/mdindex-all.jar',
        'CONF' : '/Users/anil/Dev/repos/mdindex/conf/lineitem.properties',
        'INPUTSDIR' : '/Users/anil/Dev/repos/tpch-dbgen/lineitem1/',
        'HDFSDIR' : '/user/mdindex/lineitem1/',
        'HOMEDIR' : '/Users/anil/',
        'HADOOPBIN' : '/Users/anil/Dev/tools/hadoop-2.6.0/bin/',
        'SAMPLINGRATE' : '0.1',
        'DELIMITER': '|',
        'NUMTUPLES': '6001215',
        'NUMBUCKETS' : '16',
        'NUMFIELDS' : '16',
        'SCHEMA': 'l_orderkey long, l_partkey int, l_suppkey int, l_linenumber int, l_quantity double, l_extendedprice double, l_discount double, l_tax double, l_returnflag string,  l_linestatus string, l_shipdate date, l_commitdate date, l_receiptdate date, l_shipinstruct string, l_shipmode string, l_comment string',
        'USER': 'anil',
        'HOSTS': ['localhost'],
        'ROLEDEFS': { 'master': 'localhost' }
    },
    "lineitem": {
        'JAR' : '/data/mdindex/jars/mdindex-all.jar',
        'CONF' : '/home/mdindex/cartilage.properties',
        'INPUTSDIR' : '/data/mdindex/lineitem1000/',
        'HDFSDIR' : '/user/mdindex/lineitem1000/',
        'HOMEDIR' : '/home/mdindex/',
        'HADOOPBIN' : '~/hadoop-2.6.0/bin/',
        'SAMPLINGRATE' : '0.0002',
        'DELIMITER': '|',
        'NUMBUCKETS' : '8192',
        'NUMTUPLES' : '6000000000',
        'NUMFIELDS' : '16',
        'SCHEMA': 'l_orderkey long, l_partkey int, l_suppkey int, l_linenumber int, l_quantity double, l_extendedprice double, l_discount double, l_tax double, l_returnflag string,  l_linestatus string, l_shipdate date, l_commitdate date, l_receiptdate date, l_shipinstruct string, l_shipmode string, l_comment string',
        'USER' : 'mdindex',
        'HOSTS' : ['istc2.csail.mit.edu', 'istc5.csail.mit.edu', 'istc6.csail.mit.edu', 'istc7.csail.mit.edu', 'istc8.csail.mit.edu', 'istc9.csail.mit.edu', 'istc10.csail.mit.edu', 'istc11.csail.mit.edu', 'istc12.csail.mit.edu', 'istc13.csail.mit.edu'],
        'ROLEDEFS' : { 'master': ['istc2.csail.mit.edu'] },
    },
    "local_tpch" : {
        'JAR' : '/Users/anil/Dev/repos/mdindex/build/libs/mdindex-all.jar',
        'CONF' : '/Users/anil/Dev/repos/mdindex/conf/tpch.properties',
        'INPUTSDIR' : '/Users/anil/Dev/repos/tpch-dbgen/tpchd1/',
        'HDFSDIR' : '/user/mdindex/tpchd1/',
        'HOMEDIR' : '/Users/anil/',
        'HADOOPBIN' : '/Users/anil/Dev/tools/hadoop-2.6.0/bin/',
        'SAMPLINGRATE' : '0.1',
        'DELIMITER': '|',
        'NUMBUCKETS' : '16',
        'NUMTUPLES': '6001215',
        'NUMFIELDS' : '38',
        'SCHEMA': 'l_linenumber int, l_quantity double, l_extendedprice double, l_discount double, l_tax double, l_returnflag string,  l_linestatus string, l_shipdate date, l_commitdate date, l_receiptdate date, l_shipinstruct string, l_shipmode string, o_orderstatus string, o_totalprice double, o_orderdate date, o_orderpriority string, o_clerk string, o_shippriority int, p_name string, p_mfgr string, p_brand string, p_type string, p_size int, p_container string, p_retailprice double, s_name string, s_address string, s_phone string, s_acctbal double, s_nation string, s_region string, c_name string, c_address string, c_phone string, c_acctbal double, c_mktsegment string, c_nation string, c_region string',
        'USER': 'anil',
        'HOSTS': ['localhost'],
        'ROLEDEFS': { 'master': ['localhost'] }
    },
    "tpch": {
        'JAR' : '/data/mdindex/jars/mdindex-all.jar',
        'CONF' : '/home/mdindex/tpch.properties',
        'INPUTSDIR' : '/data/mdindex/tpchd100/',
        'HDFSDIR' : '/user/mdindex/tpchd100/',
        'HOMEDIR' : '/home/mdindex/',
        'HADOOPBIN' : '~/hadoop-2.6.0/bin/',
        'SAMPLINGRATE' : '0.002',
        'DELIMITER': '|',
        'NUMBUCKETS' : '4096',
        'NUMTUPLES' : '600000000',
        'NUMFIELDS' : '38',
        'SCHEMA': 'l_linenumber int, l_quantity double, l_extendedprice double, l_discount double, l_tax double, l_returnflag string,  l_linestatus string, l_shipdate date, l_commitdate date, l_receiptdate date, l_shipinstruct string, l_shipmode string, o_orderstatus string, o_totalprice double, o_orderdate date, o_orderpriority string, o_clerk string, o_shippriority int, p_name string, p_mfgr string, p_brand string, p_type string, p_size int, p_container string, p_retailprice double, s_name string, s_address string, s_phone string, s_acctbal double, s_nation string, s_region string, c_name string, c_address string, c_phone string, c_acctbal double, c_mktsegment string, c_nation string, c_region string',
        'USER' : 'mdindex',
        'HOSTS' : ['istc2.csail.mit.edu', 'istc5.csail.mit.edu', 'istc6.csail.mit.edu', 'istc7.csail.mit.edu', 'istc8.csail.mit.edu', 'istc9.csail.mit.edu', 'istc10.csail.mit.edu', 'istc11.csail.mit.edu', 'istc12.csail.mit.edu', 'istc13.csail.mit.edu'],
        'ROLEDEFS' : { 'master': ['istc2.csail.mit.edu'] },
    },
    "local_cmt" : {
        'JAR' : '/Users/anil/Dev/repos/mdindex/build/libs/mdindex-all.jar',
        'CONF' : '/Users/anil/Dev/repos/mdindex/conf/cmt.properties',
        'INPUTSDIR' : '/Users/anil/Dev/data/cmt1/',
        'HDFSDIR' : '/user/mdindex/cmt1/',
        'HOMEDIR' : '/Users/anil/',
        'HADOOPBIN' : '/Users/anil/Dev/tools/hadoop-2.6.0/bin/',
        'SAMPLINGRATE' : '0.1',
        'DELIMITER': '$',
        'NUMBUCKETS' : '16',
        'NUMTUPLES': '500000',
        'NUMFIELDS' : '148',
        'SCHEMA': 'mh_id int,mh_dataset_id string,mh_uploadtime date,mh_runtime string,mh_trip_start date,mh_data_count_minutes string,mh_data_count_accel_samples string,mh_data_count_netloc_samples string,mh_data_count_gps_samples string,mh_observed_sample_rate string,mh_distance_mapmatched_km string,mh_distance_gps_km string,mh_ground_truth_present string,mh_timing_mapmatch string,mh_distance_pct_path_error string,mh_build_version string,mh_timing_queue_wait string,mh_data_trip_length string,mh_battery_maximum_level string,mh_battery_minimum_level string,mh_battery_drain_rate_per_hour string,mh_battery_plugged_duration_hours string,mh_battery_delay_from_drive_end_seconds string,mh_startlat string,mh_startlon string,mh_endlat string,mh_endlon string,mh_data_count_output_gps_speeding_points string,mh_speeding_slow_gps_points string,mh_speeding_10kmh_gps_points string,mh_speeding_20kmh_gps_points string,mh_speeding_40kmh_gps_points string,mh_speeding_80kmh_gps_points string,mh_output_accel_valid_minutes string,mh_output_gps_moving_minutes string,mh_output_gps_moving_and_accel_valid_minutes string,mh_data_time_till_first_gps_minutes string,mh_score_di_accel string,mh_score_di_brake string,mh_score_di_turn string,mh_score_di_car_motion string,mh_score_di_phone_motion string,mh_score_di_speeding string,mh_score_di_night string,mh_star_rating string,mh_trip_end date,mh_score_di_car_motion_with_accel string,mh_score_di_car_motion_with_speeding string,mh_score_di_distance_km_with_accel string,mh_score_di_distance_km_with_speeding string,mh_score_accel_per_sec_ntile string,mh_score_brake_per_sec_ntile string,mh_score_turn_per_sec_ntile string,mh_score_speeding_per_sec_ntile string,mh_score_phone_motion_per_sec_ntile string,mh_score_accel_per_km_ntile string,mh_score_brake_per_km_ntile string,mh_score_turn_per_km_ntile string,mh_score_speeding_per_km_ntile string,mh_score_phone_motion_per_km_ntile string,mh_score string,mh_distance_prepended_km string,mh_recording_start date,mh_score_di_distance_km string,mh_recording_end date,mh_recording_startlat string,mh_recording_startlon string,mh_display_distance_km string,mh_display_trip_start date,mh_display_startlat string,mh_display_startlon string,mh_data_count_gyro_samples string,mh_star_rating_accel string,mh_star_rating_brake string,mh_star_rating_turn string,mh_star_rating_speeding string,mh_star_rating_phone_motion string,mh_is_night string,mh_battery_total_drain string,mh_battery_total_drain_duration_hours string,mh_score_smoothness string,mh_score_awareness string,mh_star_rating_night string,mh_star_rating_smoothness string,mh_star_rating_awareness string,mh_hide string,mh_data_count_tag_accel_samples string,mh_quat_i string,mh_quat_j string,mh_quat_k string,mh_quat_r string,mh_passenger_star_rating string,mh_suspension_damping_ratio string,mh_suspension_natural_frequency string,mh_suspension_fit_error string,mh_driving string,mh_trip_mode string,mh_classification_confidence string,mh_gk_trip_mode string,mh_gk_confidence string,mh_offroad_trip_mode string,mh_offroad_confidence string,mh_driver_confidence string,mh_timing_processing_preprocessing string,mh_timing_processing_gatekeeper string,mh_timing_processing_accelpipeline string,mh_timing_processing_offroad string,mh_timing_processing_suspension string,mh_timing_processing_scoring string,mh_timing_processing_hitchhiker string,mh_data_count_obd_samples string,mh_data_count_pressure_samples string,mh_raw_sampling_mode string,mh_data_count_magnetometer_samples string,mh_location_disabled_date date,sf_id int,sf_uploadtime date,sf_deviceid string,sf_driveid string,sf_state string,sf_dest_server string,sf_companyid string,sf_hardware_manufacturer string,sf_hardware_model string,sf_hardware_bootloader string,sf_hardware_build string,sf_hardware_carrier string,sf_android_fw_version string,sf_android_api_version string,sf_android_codename string,sf_android_baseband string,sf_raw_hardware_string string,sf_raw_os_string string,sf_utc_offset_with_dst string,sf_app_version string,sf_file_format string,sf_start_reason string,sf_stop_reason string,sf_previous_driveid string,sf_userid string,sf_tag_mac_address string,sf_tag_trip_number string,sf_primary_driver_app_user_id string,sf_tag_last_connection_number string,sf_gps_points_lsh_key_1 string,sf_gps_points_lsh_key_2 string,sf_gps_points_lsh_key_3 string,sf_hidden_by_support string',
        'USER': 'anil',
        'HOSTS': ['localhost'],
        'ROLEDEFS': { 'master': ['localhost'] }
    },
    "cmt": {
        'JAR' : '/data/mdindex/jars/mdindex-all.jar',
        'CONF' : '/home/mdindex/cmt.properties',
        'INPUTSDIR' : '/data/mdindex/cmt100/',
        'HDFSDIR' : '/user/mdindex/cmtd100/',
        'HOMEDIR' : '/home/mdindex/',
        'HADOOPBIN' : '~/hadoop-2.6.0/bin/',
        'SAMPLINGRATE' : '0.004',
        'DELIMITER': '$',
        'NUMBUCKETS' : '2048',
        'NUMTUPLES' : '100000000',
        'NUMFIELDS' : '148',
        'SCHEMA': 'mh_id int,mh_dataset_id string,mh_uploadtime date,mh_runtime string,mh_trip_start date,mh_data_count_minutes string,mh_data_count_accel_samples string,mh_data_count_netloc_samples string,mh_data_count_gps_samples string,mh_observed_sample_rate string,mh_distance_mapmatched_km string,mh_distance_gps_km string,mh_ground_truth_present string,mh_timing_mapmatch string,mh_distance_pct_path_error string,mh_build_version string,mh_timing_queue_wait string,mh_data_trip_length string,mh_battery_maximum_level string,mh_battery_minimum_level string,mh_battery_drain_rate_per_hour string,mh_battery_plugged_duration_hours string,mh_battery_delay_from_drive_end_seconds string,mh_startlat string,mh_startlon string,mh_endlat string,mh_endlon string,mh_data_count_output_gps_speeding_points string,mh_speeding_slow_gps_points string,mh_speeding_10kmh_gps_points string,mh_speeding_20kmh_gps_points string,mh_speeding_40kmh_gps_points string,mh_speeding_80kmh_gps_points string,mh_output_accel_valid_minutes string,mh_output_gps_moving_minutes string,mh_output_gps_moving_and_accel_valid_minutes string,mh_data_time_till_first_gps_minutes string,mh_score_di_accel string,mh_score_di_brake string,mh_score_di_turn string,mh_score_di_car_motion string,mh_score_di_phone_motion string,mh_score_di_speeding string,mh_score_di_night string,mh_star_rating string,mh_trip_end date,mh_score_di_car_motion_with_accel string,mh_score_di_car_motion_with_speeding string,mh_score_di_distance_km_with_accel string,mh_score_di_distance_km_with_speeding string,mh_score_accel_per_sec_ntile string,mh_score_brake_per_sec_ntile string,mh_score_turn_per_sec_ntile string,mh_score_speeding_per_sec_ntile string,mh_score_phone_motion_per_sec_ntile string,mh_score_accel_per_km_ntile string,mh_score_brake_per_km_ntile string,mh_score_turn_per_km_ntile string,mh_score_speeding_per_km_ntile string,mh_score_phone_motion_per_km_ntile string,mh_score string,mh_distance_prepended_km string,mh_recording_start date,mh_score_di_distance_km string,mh_recording_end date,mh_recording_startlat string,mh_recording_startlon string,mh_display_distance_km string,mh_display_trip_start date,mh_display_startlat string,mh_display_startlon string,mh_data_count_gyro_samples string,mh_star_rating_accel string,mh_star_rating_brake string,mh_star_rating_turn string,mh_star_rating_speeding string,mh_star_rating_phone_motion string,mh_is_night string,mh_battery_total_drain string,mh_battery_total_drain_duration_hours string,mh_score_smoothness string,mh_score_awareness string,mh_star_rating_night string,mh_star_rating_smoothness string,mh_star_rating_awareness string,mh_hide string,mh_data_count_tag_accel_samples string,mh_quat_i string,mh_quat_j string,mh_quat_k string,mh_quat_r string,mh_passenger_star_rating string,mh_suspension_damping_ratio string,mh_suspension_natural_frequency string,mh_suspension_fit_error string,mh_driving string,mh_trip_mode string,mh_classification_confidence string,mh_gk_trip_mode string,mh_gk_confidence string,mh_offroad_trip_mode string,mh_offroad_confidence string,mh_driver_confidence string,mh_timing_processing_preprocessing string,mh_timing_processing_gatekeeper string,mh_timing_processing_accelpipeline string,mh_timing_processing_offroad string,mh_timing_processing_suspension string,mh_timing_processing_scoring string,mh_timing_processing_hitchhiker string,mh_data_count_obd_samples string,mh_data_count_pressure_samples string,mh_raw_sampling_mode string,mh_data_count_magnetometer_samples string,mh_location_disabled_date date,sf_id int,sf_uploadtime date,sf_deviceid string,sf_driveid string,sf_state string,sf_dest_server string,sf_companyid string,sf_hardware_manufacturer string,sf_hardware_model string,sf_hardware_bootloader string,sf_hardware_build string,sf_hardware_carrier string,sf_android_fw_version string,sf_android_api_version string,sf_android_codename string,sf_android_baseband string,sf_raw_hardware_string string,sf_raw_os_string string,sf_utc_offset_with_dst string,sf_app_version string,sf_file_format string,sf_start_reason string,sf_stop_reason string,sf_previous_driveid string,sf_userid string,sf_tag_mac_address string,sf_tag_trip_number string,sf_primary_driver_app_user_id string,sf_tag_last_connection_number string,sf_gps_points_lsh_key_1 string,sf_gps_points_lsh_key_2 string,sf_gps_points_lsh_key_3 string,sf_hidden_by_support string',
        'USER' : 'mdindex',
        'HOSTS' : ['istc2.csail.mit.edu', 'istc5.csail.mit.edu', 'istc6.csail.mit.edu', 'istc7.csail.mit.edu', 'istc8.csail.mit.edu', 'istc9.csail.mit.edu', 'istc10.csail.mit.edu', 'istc11.csail.mit.edu', 'istc12.csail.mit.edu', 'istc13.csail.mit.edu'],
        'ROLEDEFS' : { 'master': ['istc2.csail.mit.edu'] },
    }
}
