#!/bin/sh

~/spark-1.6.0-bin-hadoop2.6/bin/spark-submit --class perf.benchmark.Amoeba --executor-memory 200G --executor-cores 4 --master spark://istc1.csail.mit.edu:7077 ~/yilu/mdindex/build/libs/AdaptDB-all.jar customer tpch3 /user/yilu/tpch1000-amoeba/trees/customer_tpch3/index
~/spark-1.6.0-bin-hadoop2.6/bin/spark-submit --class perf.benchmark.Amoeba --executor-memory 200G --executor-cores 4 --master spark://istc1.csail.mit.edu:7077 ~/yilu/mdindex/build/libs/AdaptDB-all.jar customer tpch8 /user/yilu/tpch1000-amoeba/trees/customer_tpch8/index
~/spark-1.6.0-bin-hadoop2.6/bin/spark-submit --class perf.benchmark.Amoeba --executor-memory 200G --executor-cores 4 --master spark://istc1.csail.mit.edu:7077 ~/yilu/mdindex/build/libs/AdaptDB-all.jar orders tpch8 /user/yilu/tpch1000-amoeba/trees/orders/index
~/spark-1.6.0-bin-hadoop2.6/bin/spark-submit --class perf.benchmark.Amoeba --executor-memory 200G --executor-cores 4 --master spark://istc1.csail.mit.edu:7077 ~/yilu/mdindex/build/libs/AdaptDB-all.jar part tpch8 /user/yilu/tpch1000-amoeba/trees/part/index
~/spark-1.6.0-bin-hadoop2.6/bin/spark-submit --class perf.benchmark.Amoeba --executor-memory 200G --executor-cores 4 --master spark://istc1.csail.mit.edu:7077 ~/yilu/mdindex/build/libs/AdaptDB-all.jar supplier tpch8 /user/yilu/tpch1000-amoeba/trees/supplier/index
~/spark-1.6.0-bin-hadoop2.6/bin/spark-submit --class perf.benchmark.Amoeba --executor-memory 200G --executor-cores 4 --master spark://istc1.csail.mit.edu:7077 ~/yilu/mdindex/build/libs/AdaptDB-all.jar lineitem tpch3 /user/yilu/tpch1000-amoeba/trees/lineitem_tpch3/index
~/spark-1.6.0-bin-hadoop2.6/bin/spark-submit --class perf.benchmark.Amoeba --executor-memory 200G --executor-cores 4 --master spark://istc1.csail.mit.edu:7077 ~/yilu/mdindex/build/libs/AdaptDB-all.jar lineitem tpch10 /user/yilu/tpch1000-amoeba/trees/lineitem_tpch10/index
~/spark-1.6.0-bin-hadoop2.6/bin/spark-submit --class perf.benchmark.Amoeba --executor-memory 200G --executor-cores 4 --master spark://istc1.csail.mit.edu:7077 ~/yilu/mdindex/build/libs/AdaptDB-all.jar lineitem tpch12 /user/yilu/tpch1000-amoeba/trees/lineitem_tpch12/index
~/spark-1.6.0-bin-hadoop2.6/bin/spark-submit --class perf.benchmark.Amoeba --executor-memory 200G --executor-cores 4 --master spark://istc1.csail.mit.edu:7077 ~/yilu/mdindex/build/libs/AdaptDB-all.jar lineitem tpch14 /user/yilu/tpch1000-amoeba/trees/lineitem_tpch14/index
~/spark-1.6.0-bin-hadoop2.6/bin/spark-submit --class perf.benchmark.Amoeba --executor-memory 200G --executor-cores 4 --master spark://istc1.csail.mit.edu:7077 ~/yilu/mdindex/build/libs/AdaptDB-all.jar lineitem tpch19 /user/yilu/tpch1000-amoeba/trees/lineitem_tpch19/index